codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
    # Directory in which to execute codecov.sh
    working-directory: # optional
    # Custom Derived Data Path for Coverage.profdata and gcov processing
    xcode_derived_data: # optional
    # Specify packages to build coverage. Uploader will only build these packages
    xcode_package: # optional
